### ISSUE TITLE
Script stops at line 39 in jquery.tweetscroll.js

### ISSUE THREAD

**Issue by bartderijk** [pixel-industry/TweetScroll---jQuery-plugin#1]
Hi,

I'm installing the plugin but it looks like the script stops at line 39 in jquery.tweetscroll.js which states ' return this.each(function (options) {'. 

I can do console.log up until line 38, any ideas on what the problem might be? Thanks!

**Comment by pixel-industry** [comment]
Hi,
What error you get in console?

**Comment by bartderijk** [comment]
I already fixed it with a workaround, I commented 39 out and gave a direct selector to the createhtml method. The error in my console was saying something like 'error in line 98, can't do the loop'. Thanks though!

**Comment by pixel-industry** [comment]
Thanks for you feedback. I will take a look why is this happening.

Vladimir

**Comment by bartderijk** [comment]
For the working thing, with workaround, check out www.ageethdehaan.nl
