### ISSUE TITLE
it is not working on lots of server does it require curl or kind of thing enabled

### ISSUE THREAD

**Issue by iRealNirmal** [pixel-industry/TweetScroll---jQuery-plugin#8]
I have put this code over 4 server but it worked only in one server. What is the requirement of it ?

**Comment by pixel-industry** [comment]
Hi,

Sorry for late reply. Plugin doesn't have any special requirements. It makes requests to APIs and generates HTML. You just need to have PHP enabled on your server.

**Comment by iRealNirmal** [comment]
I tried on multiple server it worked on only two of it.

On Thu, Jul 16, 2015 at 5:23 PM, Pixel Industry notifications@github.com
wrote:

> Hi,
> 
> Sorry for late reply. Plugin doesn't have any special requirements. It
> makes requests to APIs and generates HTML.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixel-industry/TweetScroll---jQuery-plugin/issues/8#issuecomment-121935431
> .

## 

With Regards,
Nirmal Bhagwani.

**Comment by pixel-industry** [comment]
You can check in console if there are any errors when request is sent. That might help giving some light on this issue.

**Comment by iRealNirmal** [comment]
Ohh don't know but now I can see it's working. Whatever was reason bu it's working now.
